
// NOTE: we assume jQuery is already loaded on the page...

/* This code will load the metadata.json (generated by Frog) and use it to
 * decorate every page with the tags drop-down menu and generate a sidebar of
 * recent posts for every blog post -- Frog used to generate these directly in
 * the HTML, but this meant that every blog page had to change when a new blog
 * post was added...
 */

var posts_in_sidebar = 20;

tag_entry = function(tag) {
    return ('<a class="dropdown-item" href="' + tag.url +'">'
            + tag.name + '&nbsp<small>(' + tag.count + ')</small></a>');
};

post_entry = function(post) {
    var d1 = new Date(post.date * 1000);
    var d2 = (d1.getFullYear().toString() + '-'
              + (d1.getMonth() + 1).toString() + '-'
              + d1.getDate().toString());
    return ('<a href="' + post.url + '">' + post.title
            + '</a>&nbsp<small class="date-and-tags">' + d2 + '</small>');
}

$(document).ready(function() {
    $.ajax({
        type: 'GET',
        url: '/metadata.json',
        success: function(result) {
            var td = $('#tags-menu-content');
            if (td) {
                $.each(result.tags, function(index, tag) {
                    td.append('<li>' + tag_entry(tag) + '</li>');
                });
            }
            var rp = $('#sidebar-content');
            if (rp) {
                rp.append('<h3 class="index-entry">Recent Posts</h3>');
                $.each(result.posts.reverse(), function(index, post) {
                    if (index < posts_in_sidebar) {
                        rp.append('<p>' + post_entry(post) + '</p>');
                    }
                });
            }
        }
    });
});
