
// NOTE: we assume jQuery is already loaded on the page...

/* This code will load the metadata.json (generated by Frog) and use it to
 * decorate every page with the tags drop-down menu and generate a sidebar of
 * recent posts for every blog post -- Frog used to generate these directly in
 * the HTML, but this meant that every blog page had to change when a new blog
 * post was added...
 */

var posts_in_sidebar = 20;

tag_entry = function(tag) {
    return ('<a class="dropdown-item" href="' + tag.url +'">'
            + tag.name + '&nbsp<small>(' + tag.count + ')</small></a>');
};

fmt_ago = function(v, plural, singular) {
    if (v > 1.5) {
        return Math.round(v) + " " + plural + " ago";
    }
    else {
        return "a " + singular + " ago";
    }
};

ago = function(date) {
    var diff = Date.now() - date;
    if (diff > (11.5 * 30 * 24 * 3600 * 1000)) {
        var v = diff / (365 * 24 * 3600 * 1000);
        return fmt_ago(v, "years", "year");
    }
    else if (diff > (0.5 * 30 * 24 * 3600 * 1000)) {
        var v = diff / (30 * 24 * 3600 * 1000);
        return fmt_ago(v, "months", "month");
    }
    else if (diff > (6.5 * 24 * 3600 * 1000)) {
        var v = diff / (7 * 24 * 3600 * 1000);
        return fmt_ago(v, "weeks", "week");
    }
    else if (diff > (23.5 * 3600 * 1000)) {
        var v = diff / (24 * 3600 * 1000);
        return fmt_ago(v, "days", "day");
    }
    else {
        // this is a blog, don't care about smaller durations
        return "less than a day ago";
    }
}

post_entry = function(post) {
    return ('<a href="' + post.url + '">' + post.title
            + '</a><br><small class="date-and-tags">published '
            + ago(new Date(post.date * 1000))
            + '</small>');
}

$(document).ready(function() {
    $.ajax({
        type: 'GET',
        url: '/metadata.json',
        success: function(result) {
            var td = $('#tags-menu-content');
            if (td) {
                $.each(result.tags, function(index, tag) {
                    td.append('<li>' + tag_entry(tag) + '</li>');
                });
            }
            var rp = $('#sidebar-content');
            if (rp) {
                rp.append('<h3 class="index-entry">Recent Posts</h3>');
                $.each(result.posts.reverse(), function(index, post) {
                    if (index < posts_in_sidebar) {
                        rp.append('<p>' + post_entry(post) + '</p>');
                    }
                });
            }
        }
    });
});
